[cdse]
# Copernicus Dataspace credentials
# OAuth client – create at: https://shapps.dataspace.copernicus.eu/dashboard/
client_id     = sh-ebbb3852-8bb2-4942-97d3-d4007d3cab71
client_secret = yGrJUb62nvmu2yRyMgI3kF5CQBFdvHfg
 
# Dataspace account (email + password) – required for download
username = 2a7a7a11-7306-4c63-b7df-df9e23bf74f7
password = Dobruska.cechy0907