"""
Levee Detection - Patch Loader
===============================

Loads .npz patch files generated by 01_generate_patches.py
and displays the first N patches with their channels.

Author:   Jakub Zapletal
Date:     2026-04-13
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Config
# ------------------------------------------------------------
PATCHES_DIR = Path(
    r"D:\90_PersonalFoldlers\JZa\DataProcessing\levees_detection\geomorphological_ML\patches_v01\patches"
)
N_PATCHES = 5


# ------------------------------------------------------------
# Load first N .npz files
# ------------------------------------------------------------
npz_files = sorted(PATCHES_DIR.glob("*.npz"))[:N_PATCHES]
print(
    f"Found {len(list(PATCHES_DIR.glob('*.npz')))} total .npz files, loading first {N_PATCHES}:\n"
)

patches = []
for f in npz_files:
    data = dict(np.load(f))
    patches.append({"name": f.stem, "data": data})
    keys = list(data.keys())
    shapes = {k: v.shape for k, v in data.items()}
    print(f"  {f.name}  channels={keys}  shapes={shapes}")


# ------------------------------------------------------------
# Plot
# ------------------------------------------------------------
n_channels = len(patches[0]["data"])
fig, axes = plt.subplots(
    N_PATCHES, n_channels, figsize=(3 * n_channels, 3 * N_PATCHES), squeeze=False
)

channel_names = list(patches[0]["data"].keys())

for row, patch in enumerate(patches):
    for col, ch_name in enumerate(channel_names):
        ax = axes[row, col]
        arr = patch["data"][ch_name]
        if ch_name == "label":
            ax.imshow(arr, cmap="Reds", interpolation="nearest")
        else:
            ax.imshow(arr, cmap="terrain", interpolation="nearest")
        if row == 0:
            ax.set_title(ch_name)
        if col == 0:
            ax.set_ylabel(patch["name"], fontsize=8)
        ax.set_xticks([])
        ax.set_yticks([])

plt.tight_layout()
plt.show()
