[project]
name = "geo-approach"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pixi.workspace]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["win-64"]

[tool.pixi.dependencies]
pip = ">=26.0.1,<27"
hydromt_sfincs = ">=1.0.3,<2"
python = ">=3.14.6,<3.15"
geopandas = ">=1.1.4,<2"
pandas = ">=3.0.3,<4"

