[project]
name = "geo-approach"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pixi.workspace]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["win-64"]

[tool.pixi.dependencies]
pip = ">=26.0.1,<27"
python = ">=3.12,<3.13"
geopandas = ">=1.0,<2"
pandas = ">=2.0,<3"
hydromt = ">=1.4.0,<2"
pyflwdir = "*"

[tool.pixi.pypi-dependencies]
hydromt_sfincs = ">=2.0.0rc3"