[workspace]
channels = ["conda-forge"]
name = "01_Extract_FLPL"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
sqlalchemy = ">=2.0.50,<3"
python = ">=3.12,<3.13"
pandas = ">=3.0.2,<4"
geopandas = ">=1.1.3,<2"
ipykernel = ">=7.2.0,<8"
jupyter = ">=1.1.1,<2"
pyodbc = ">=5.3.0,<6"
gdal = ">=3.12.3,<4"
pyflwdir = ">=0.5.11,<0.6"
pip = ">=26.1.1,<27"
tqdm = ">=4.67.3,<5"
lxml = ">=6.1.0,<7"
geojson = ">=3.2.0,<4"
fiona = ">=1.10.1,<2"
numpy = ">=1,<2"
scikit-image = ">=0.19,<1"
openpyxl = ">=3.1.5,<4"
psycopg2 = ">=2.9.12,<3"

[pypi-dependencies]
pysheds = ">=0.5,<0.6"
